### ISSUE TITLE
[BUG] error: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.0-rust-1.65.0-stable' Reader: 'LLVM 14.0.6')

### ISSUE THREAD

**Issue by Scofield-04-21-076** [blocksecteam/rustle#14]
***Perhaps someone has encountered this problem and can help.***

I install the necessary toolsets using the following commands:

> # install Rust Toolchain
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
>
> # install LLVM 14
> wget https://apt.llvm.org/llvm.sh
> chmod +x llvm.sh
> sudo ./llvm.sh 14
> rm llvm.sh
>
> # install Python toolchain
> sudo apt install python3 python3-pip python3-tk   
> pip3 install -r utils/requirements.txt  # you need to clone this repo first
>
> # add WASM target
> rustup target add wasm32-unknown-unknown
>
> # install other components
> sudo apt install libudev-dev figlet
> cargo install rustfilt

(There were no problems with installing the necessary toolsets)

Then I run the following commands:
># clone LiNEAR
>git clone https://github.com/linear-protocol/LiNEAR.git ~/near-repo/LiNEAR
>
># run Rustle
>./rustle -t ~/near-repo/LiNEAR ~/near-repo/LiNEAR/contracts/linear

I get the following errors during execution:
>/usr/lib/llvm-14/bin/opt: /home/user/RUST_project/near-repo/LiNEAR/target/wasm32-unknown-unknown/debug/deps/linear.bc: error: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.0-rust-1.65.0-stable' Reader: 'LLVM 14.0.6')
make: *** [Makefile:211: unhandled-promise] Error 123
>/usr/lib/llvm-14/bin/opt: /home/user/RUST_project/near-repo/LiNEAR/target/wasm32-unknown-unknown/debug/deps/linear.bc: error: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.0-rust-1.65.0-stable' Reader: 'LLVM 14.0.6')
make: *** [Makefile:120: reentrancy] Error 123
>/usr/lib/llvm-14/bin/opt: /home/user/RUST_project/near-repo/LiNEAR/target/wasm32-unknown-unknown/debug/deps/linear.bc: error: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.0-rust-1.65.0-stable' Reader: 'LLVM 14.0.6')
make: *** [Makefile:181: self-transfer] Error 123
> ...

As a result, I get:
>Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.callback.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.promise-result.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.ext-call.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.reentrancy.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.complex-loop.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.transfer.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.round.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.div-before-mul.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.unsafe-math.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.upgrade-func.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.self-transfer.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.timestamp.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.prepaid-gas.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.unhandled-promise.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.yocto-attach.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.unused-ret.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.lock-callback.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.non-callback-private.tmp'
Tmp log not found:  [Errno 2] No such file or directory: '/home/user/RUST_project/rustle_1/.tmp//.non-private-callback.tmp'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:03<00:00,  6.74it/s]

Environment Details:
OS: Linux Mint 21

**Comment by FUTURETECH6** [comment]
The latest stable version of Rust (1.65.0) bumped LLVM version to 15.0 several days ago. But we haven't updated the LLVM version Rustle use. Try `rustup default 1.64.0` to downgrade the Rust version.

**Comment by FUTURETECH6** [comment]
btw, don't forget `rustup target add wasm32-unknown-unknown` to add the target after changing Rust version

**Comment by Scofield-04-21-076** [comment]
Thank you!
