### ISSUE TITLE
Add `-o` option to specify output folder of auditing results

### ISSUE THREAD

**Issue by think-in-universe** [blocksecteam/rustle#3]
Now when running Rustle, the output folder is `./audit-result` in the local folder of Rustle. The result will be overwritten if running auditing against multiple contracts. 

It would be helpful to provide a `-o` option to specify the auditing result output folder. 

```bash
# run Rustle
./rustle -t ~/near-repo/LiNEAR ~/near-repo/LiNEAR/contracts/linear
```

=> 

```bash
# run Rustle
./rustle -t ~/near-repo/LiNEAR ~/near-repo/LiNEAR/contracts/linear -o ~/near-repo/LiNEAR/.auditing
```

**Comment by FUTURETECH6** [comment]
fixed in 46da60e4709ee13ce2d27745df930f0a6bbb079e
