### ISSUE TITLE
 Question about detectors/Makefile compilation command and understanding LLVM code in detectors

### ISSUE THREAD

**Issue by Usman-CrYpToo** [blocksecteam/rustle#31]
Question:
I've been exploring the detectors/Makefile in the Rustle repository and noticed a rule that compiles near_core.cpp and near_core.h into a .so (shared object) file using the following command:

`$(LLVM_CLANG) ${CXXFLAGS} $< near_core.cpp -o $@ ${LDFLAGS}`

Could someone kindly explain why near_core.cpp and near_core.h are specifically used in this compilation process? What role do these files play in the context of the detectors module?

Additionally, I'm curious about the purpose of each part of this compilation command ($<, near_core.cpp, -o $@, ${CXXFLAGS}, ${LDFLAGS}). How do these components contribute to the generation of the .so file?

Any insights or explanations regarding the rationale behind including these files and how they fit into the overall detector framework would be greatly appreciated.

Additionally, I'm looking to gain a better understanding of the LLVM code within the detector. How can I interpret and analyze the LLVM code generated by this compilation process?

Any insights, explanations, or guidance would be greatly appreciated!

**Comment by futuretech6** [comment]
1. The near_core.cpp file offers numerous essential features for the high-level detectors.
2. For further information on makefile automatic variables, you may refer to https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html.
3. The LLVM-IR code should reside within the "target/" directory of the target project, you can check it yourself.
