### ISSUE TITLE
In the result `summary.csv`, add a `severity` column

### ISSUE THREAD

**Issue by think-in-universe** [blocksecteam/rustle#4]
Add a `severity` column with `high`, `med`, `low`, and `info` level to make it easier to filter issues. 

Also add the `severity` field to `summary.json`.

**Comment by FUTURETECH6** [comment]
What do you mean by `Add a severity column`? We now have classified vulnerabilities into four groups. Refer to [README](https://github.com/blocksecteam/rustle#detectors) for more details.

**Comment by FUTURETECH6** [comment]
> Also add the severity field to summary.json.

Add in ef076d3

**Comment by think-in-universe** [comment]
I mean `severity` level like `critical`, `high`, `med`, `low`, `info`, etc.

**Comment by FUTURETECH6** [comment]
Ok, then that's added. I will close this issue,
